  CART_8KB(1, "Asteroids"),
  CART_8KB(2, "Centipede"),
  CART_8KB(3, "Computer Chess"),
  CART_8KB(4, "Frogger"),
  CART_8KB(5, "Galaxian"),
  CART_8KB(6, "Pac-Man"),
  CART_8KB(7, "Pitfall!"),
  CART_8KB(8, "River Raid"),
  CART_8KB(9, "Space Invaders"),
  CART_16KB(11, "Dig Dug"),
  CART_16KB(13, "Donkey Kong Junior"),
  CART_16KB(15, "Donkey Kong"),
  CART_16KB(17, "Montezuma's Revenge"),
  CART_16KB(19, "Moon Patrol"),
  CART_16KB(21, "Pitfall! II - Lost Caverns")
